[build]
  # Directory to publish
  publish = "./"
  # Add a simple build command to trigger our plugin
  command = "echo 'Running build process to inject environment variables'"

# Environment variables - consider moving sensitive keys to Netlify UI
[build.environment]
  NODE_VERSION = "16.15.0"

# Use our custom plugin to inject environment variables
[[plugins]]
  package = "./netlify-plugin-env.js"

# Redirect all 404s to the index page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for static assets
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"  # 7 days

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"  # 1 day

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"  # 1 day

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"   # 1 hour
    Access-Control-Allow-Origin = "*"        # Allow cross-origin access

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Content-Security-Policy = "default-src 'self' https://api.mapbox.com https://events.mapbox.com https://*.tiles.mapbox.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https://api.mapbox.com https://*.tiles.mapbox.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://api.mapbox.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://api.mapbox.com https://cdnjs.cloudflare.com; connect-src 'self' https://api.mapbox.com https://*.tiles.mapbox.com;"

# Enable branch deploy previews
[context.branch-deploy]
  command = ""

# Define specific settings for production
[context.production]
  command = ""

# Enable Netlify's asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
